# In the terminal execute the following commands:
# docker-compose build
# docker-compose up
# this will start mongo database and the web server

version: "3.3"
services:
  mongo:
    image: mongo:4.2.5
    ports:
      - "27017:27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        WAIT_HOSTS: mongo:27017
    ports:
      - "5000:5000"
    